// examples/svelte-examples/src/App.svelte
<script lang="ts">
	import ContextParent from "./ContextParent.svelte";
	import LazyStepsExample from "./LazyStepsExample.svelte";
	import RunesExample from "./RunesExample.svelte";
	import StoreExample from "./StoreExample.svelte";

	type Tab = "store" | "runes" | "context" | "lazy";

	const TABS: Array<{ id: Tab; label: string }> = [
		{ id: "store", label: "Store API" },
		{ id: "runes", label: "Runes API" },
		{ id: "context", label: "Context" },
		{ id: "lazy", label: "Lazy Steps" },
	];

	let tab = $state<Tab>("store");
</script>

<main>
	<h1>WizardForm — Svelte examples</h1>
	<p class="lede">
		The same wizard driven by both layers of <code>@gooonzick/wizard-svelte</code>.
		Switching tabs unmounts the previous demo, which destroys its machine — so each
		tab starts from a clean wizard.
	</p>

	<div class="tabs" role="tablist">
		{#each TABS as { id, label } (id)}
			<button
				role="tab"
				aria-selected={tab === id}
				onclick={() => {
					tab = id;
				}}
			>
				{label}
			</button>
		{/each}
	</div>

	{#if tab === "store"}
		<StoreExample />
	{:else if tab === "runes"}
		<RunesExample />
	{:else if tab === "lazy"}
		<LazyStepsExample />
	{:else}
		<ContextParent />
	{/if}
</main>

// examples/solid-examples/src/App.tsx
import { createSignal, For, Match, Switch } from "solid-js";
import { BasicExample } from "./BasicExample";
import { ContextExample } from "./ContextExample";
import { LazyStepsExample } from "./LazyStepsExample";

type Tab = "basic" | "context" | "lazy";

const TABS: Array<{ id: Tab; label: string }> = [
	{ id: "basic", label: "createWizard" },
	{ id: "context", label: "Context" },
	{ id: "lazy", label: "Lazy Steps" },
];

export function App() {
	const [tab, setTab] = createSignal<Tab>("basic");

	return (
		<main>
			<h1>WizardForm — Solid examples</h1>
			<p class="lede">
				The same wizard driven by <code>@gooonzick/wizard-solid</code>.
				Switching tabs unmounts the previous demo, which destroys its machine —
				so each tab starts from a clean wizard.
			</p>

			<div class="tabs" role="tablist">
				<For each={TABS}>
					{({ id, label }) => (
						<button
							type="button"
							role="tab"
							aria-selected={tab() === id}
							onClick={() => setTab(id)}
						>
							{label}
						</button>
					)}
				</For>
			</div>

			<Switch>
				<Match when={tab() === "basic"}>
					<BasicExample />
				</Match>
				<Match when={tab() === "context"}>
					<ContextExample />
				</Match>
				<Match when={tab() === "lazy"}>
					<LazyStepsExample />
				</Match>
			</Switch>
		</main>
	);
}
