// examples/react-examples/src/lazy-steps-example.tsx
import { WizardStepLoadError } from "@gooonzick/wizard-core";
import { useWizard } from "@gooonzick/wizard-react";
import type React from "react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { armLoadFailure, createLazyStepsWizard } from "./lazy-steps/definition";
import { lazyInitialData } from "./lazy-steps/types";

const definition = createLazyStepsWizard();

function LazyStepsWizard({ onRecreate }: { onRecreate: () => void }) {
	const [loadError, setLoadError] = useState<string | null>(null);
	const [failureArmed, setFailureArmed] = useState(false);
	const { state, navigation, validation, loading, actions } = useWizard({
		definition,
		initialData: lazyInitialData,
		onError: (error) => {
			if (error instanceof WizardStepLoadError) {
				const cause = error.cause instanceof Error ? error.cause.message : "";
				setLoadError(`${error.message}${cause ? ` — ${cause}` : ""}`);
				setFailureArmed(false);
			}
		},
		onStepEnter: () => setLoadError(null),
		onComplete: (data) => alert(`Done: ${JSON.stringify(data)}`),
	});

	const step = state.currentStep;
	const next = () => {
		setLoadError(null);
		void navigation.goNext().catch(() => {});
	};

	return (
		<Card className="p-8 space-y-4">
			<div>
				<h2 className="text-xl font-semibold">{step.meta?.title}</h2>
				<p className="text-sm text-gray-500">{step.meta?.description}</p>
			</div>

			{loading.isLoadingStep && (
				<p className="text-sm text-blue-600 animate-pulse">
					Loading step implementation…
				</p>
			)}
			{loadError && <p className="text-sm text-red-600">{loadError}</p>}

			{state.currentStepId === "account" && (
				<label className="block">
					<span className="text-sm font-medium text-gray-700">Email</span>
					<input
						className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
						value={state.data.email}
						onChange={(e) => actions.updateField("email", e.target.value)}
						placeholder="ada@example.com"
					/>
				</label>
			)}
			{state.currentStepId === "documents" && (
				<label className="block">
					<span className="text-sm font-medium text-gray-700">
						Passport number
					</span>
					<input
						className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
						value={state.data.passport}
						onChange={(e) => actions.updateField("passport", e.target.value)}
						placeholder="AB1234567"
					/>
				</label>
			)}
			{state.currentStepId === "summary" && (
				<pre className="rounded bg-gray-100 p-3 text-xs">
					{JSON.stringify(state.data, null, 2)}
				</pre>
			)}

			{validation.validationErrors &&
				Object.entries(validation.validationErrors).map(([field, msg]) => (
					<p key={field} className="text-sm text-red-600">
						{msg}
					</p>
				))}

			<div className="flex flex-wrap gap-3">
				<Button
					variant="outline"
					onClick={() => void navigation.goPrevious().catch(() => {})}
					disabled={!navigation.canGoPrevious || loading.isNavigating}
				>
					Back
				</Button>
				{navigation.isLastStep ? (
					<Button onClick={() => void actions.submit().catch(() => {})}>
						Finish
					</Button>
				) : (
					<Button
						onClick={next}
						// Prefetch the lazy step while the user is about to click.
						// Skipped while a failure is armed: a silent preload would consume it.
						onMouseEnter={() => {
							if (state.currentStepId === "account" && !failureArmed) {
								void actions.preloadStep("documents").catch(() => {});
							}
						}}
						disabled={loading.isNavigating}
					>
						{loading.isLoadingStep ? "Loading…" : "Next"}
					</Button>
				)}
			</div>

			<div className="flex flex-wrap gap-3 border-t pt-4 text-sm">
				<Button
					variant="outline"
					onClick={() => {
						armLoadFailure();
						setFailureArmed(true);
					}}
				>
					{failureArmed ? "Next load will fail" : "Fail next load"}
				</Button>
				<Button variant="outline" onClick={onRecreate}>
					Recreate wizard (forget loaded chunks)
				</Button>
			</div>
			<p className="text-xs text-gray-500">
				A loaded step is cached per wizard. Hovering “Next” on the first step
				prefetches it with <code>preloadStep</code>, so no spinner appears.
				“Fail next load” only matters before the step has loaded once —
				recreate the wizard to try it again.
			</p>
		</Card>
	);
}

export const LazyStepsExample: React.FC = () => {
	const [generation, setGeneration] = useState(0);
	return (
		<div className="min-h-screen bg-gray-50 py-8 px-4">
			<div className="max-w-3xl mx-auto">
				<h1 className="text-3xl font-bold text-gray-900">Lazy Steps</h1>
				<p className="text-gray-600 mt-1 mb-6">
					The Documents step loads its validation and lifecycle code on demand
					(WIZ-013).
				</p>
				<LazyStepsWizard
					key={generation}
					onRecreate={() => setGeneration((g) => g + 1)}
				/>
			</div>
		</div>
	);
};

// examples/solid-examples/src/LazyStepsExample.tsx
import { WizardStepLoadError } from "@gooonzick/wizard-core";
import { createWizard } from "@gooonzick/wizard-solid";
import { createSignal, For, Match, Show, Switch } from "solid-js";
import { armLoadFailure, createLazyStepsWizard } from "./lazy-steps/definition";
import { type LazyDemoData, lazyInitialData } from "./lazy-steps/types";

function LazyStepsWizard(props: { onRecreate: () => void }) {
	const [loadError, setLoadError] = createSignal<string | null>(null);
	const [failureArmed, setFailureArmed] = createSignal(false);

	const wizard = createWizard<LazyDemoData>({
		definition: createLazyStepsWizard(),
		initialData: lazyInitialData,
		onError: (error) => {
			if (error instanceof WizardStepLoadError) {
				const cause = error.cause instanceof Error ? error.cause.message : "";
				setLoadError(`${error.message}${cause ? ` — ${cause}` : ""}`);
				setFailureArmed(false);
			}
		},
		onStepEnter: () => setLoadError(null),
		onComplete: (data) => alert(`Done: ${JSON.stringify(data)}`),
	});

	const email = wizard.field("email");
	const passport = wizard.field("passport");

	const next = () => {
		setLoadError(null);
		void wizard.goNext().catch(() => {});
	};
	const prefetch = () => {
		// Skipped while a failure is armed: a silent preload would consume it.
		if (wizard.currentStepId === "account" && !failureArmed()) {
			void wizard.actions.preloadStep("documents").catch(() => {});
		}
	};

	return (
		<section class="panel">
			<h2>{wizard.currentStep.meta?.title}</h2>
			<p class="description">{wizard.currentStep.meta?.description}</p>

			<Show when={wizard.isLoadingStep}>
				<p class="description">Loading step implementation…</p>
			</Show>
			<Show when={loadError()}>
				{(message) => <p class="error">{message()}</p>}
			</Show>

			<Switch>
				<Match when={wizard.currentStepId === "account"}>
					<label>
						<span>Email</span>
						<input
							value={email.value}
							onInput={(e) => {
								email.value = e.currentTarget.value;
							}}
							placeholder="ada@example.com"
						/>
					</label>
				</Match>
				<Match when={wizard.currentStepId === "documents"}>
					<label>
						<span>Passport number</span>
						<input
							value={passport.value}
							onInput={(e) => {
								passport.value = e.currentTarget.value;
							}}
							placeholder="AB1234567"
						/>
					</label>
				</Match>
				<Match when={wizard.currentStepId === "summary"}>
					<pre class="debug">{JSON.stringify(wizard.data, null, 2)}</pre>
				</Match>
			</Switch>

			<For each={Object.entries(wizard.validationErrors ?? {})}>
				{([, message]) => <p class="error">{message}</p>}
			</For>

			<div class="controls">
				<button
					type="button"
					class="secondary"
					onClick={() => void wizard.goPrevious().catch(() => {})}
					disabled={!wizard.canGoPrevious || wizard.isNavigating}
				>
					Back
				</button>
				<Show
					when={wizard.isLastStep}
					fallback={
						<button
							type="button"
							onClick={next}
							onMouseEnter={prefetch}
							disabled={wizard.isNavigating}
						>
							{wizard.isLoadingStep ? "Loading…" : "Next"}
						</button>
					}
				>
					<button
						type="button"
						onClick={() => void wizard.actions.submit().catch(() => {})}
					>
						Finish
					</button>
				</Show>
				<span class="spacer" />
				<button
					type="button"
					class="secondary"
					onClick={() => {
						armLoadFailure();
						setFailureArmed(true);
					}}
				>
					{failureArmed() ? "Next load will fail" : "Fail next load"}
				</button>
				<button
					type="button"
					class="secondary"
					onClick={() => props.onRecreate()}
				>
					Recreate wizard
				</button>
			</div>

			<p class="description">
				A loaded step is cached per wizard; hovering “Next” on the first step
				prefetches it with <code>preloadStep</code>. “Fail next load” only
				matters before the step has loaded once — recreate the wizard to try it
				again.
			</p>
		</section>
	);
}

export function LazyStepsExample() {
	const [generation, setGeneration] = createSignal(1);
	return (
		<Show when={generation()} keyed>
			{(_generation) => (
				<LazyStepsWizard onRecreate={() => setGeneration((g) => g + 1)} />
			)}
		</Show>
	);
}
