// examples/react-examples/src/App.tsx
import { useEffect, useState } from "react";
import { AnalyticsExample } from "./analytics-example";
import { DataChangeExample } from "./data-change-example";
import { HistoryExample } from "./history-example";
import { LazyStepsExample } from "./lazy-steps-example";
import { PersistencePluginExample } from "./persistence-plugin-example";
import { PluginsExample } from "./plugins-example";
import { ProviderExample } from "./provider-example";
import { ResetCancelExample } from "./reset-cancel-example";
import { StatePersistenceExample } from "./state-persistence-example";
import { WizardExample } from "./wizard-example";

type View =
	| "wizard"
	| "provider"
	| "history"
	| "reset-cancel"
	| "persistence"
	| "persistence-plugin"
	| "plugins"
	| "analytics"
	| "data-change"
	| "lazy-steps";

const tabs: Array<{ id: View; label: string }> = [
	{ id: "wizard", label: "Registration Wizard" },
	{ id: "provider", label: "Provider + Hooks" },
	{ id: "history", label: "Navigation History" },
	{ id: "reset-cancel", label: "Reset & Cancel" },
	{ id: "persistence", label: "State Persistence" },
	{ id: "persistence-plugin", label: "Persistence Plugin" },
	{ id: "plugins", label: "Plugins" },
	{ id: "analytics", label: "Analytics" },
	{ id: "data-change", label: "Data Change" },
	{ id: "lazy-steps", label: "Lazy Steps" },
];

const VIEWS: View[] = tabs.map((tab) => tab.id);

// The selected tab survives a reload so the persistence demo can show a real
// `window.location.reload()` — mirrors the Vue app's `wizard-approach` key.
const TAB_STORAGE_KEY = "wizard-react-tab";

const readSavedView = (): View => {
	try {
		const saved = localStorage.getItem(TAB_STORAGE_KEY);
		return saved && VIEWS.includes(saved as View) ? (saved as View) : "wizard";
	} catch {
		return "wizard"; // private mode / storage disabled
	}
};

export function App() {
	// Lazy initializer: pass the function, do not call it.
	const [view, setView] = useState<View>(readSavedView);

	useEffect(() => {
		try {
			localStorage.setItem(TAB_STORAGE_KEY, view);
		} catch {
			/* ignore */
		}
	}, [view]);

	return (
		<div className="min-h-screen bg-gray-50">
			<div className="max-w-7xl mx-auto pt-4 px-4 flex flex-wrap gap-2">
				{tabs.map((tab) => (
					<button
						key={tab.id}
						type="button"
						onClick={() => setView(tab.id)}
						className={`px-4 py-2 rounded-md text-sm font-medium transition ${
							view === tab.id
								? "bg-gray-900 text-white"
								: "bg-white text-gray-700 border hover:bg-gray-50"
						}`}
					>
						{tab.label}
					</button>
				))}
			</div>
			{view === "wizard" && <WizardExample />}
			{view === "provider" && <ProviderExample />}
			{view === "history" && <HistoryExample />}
			{view === "reset-cancel" && <ResetCancelExample />}
			{view === "persistence" && <StatePersistenceExample />}
			{view === "persistence-plugin" && <PersistencePluginExample />}
			{view === "plugins" && <PluginsExample />}
			{view === "analytics" && <AnalyticsExample />}
			{view === "data-change" && <DataChangeExample />}
			{view === "lazy-steps" && <LazyStepsExample />}
		</div>
	);
}

// examples/vue-examples/src/App.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import ApproachToggle from "./components/approach-toggle.vue";
import AnalyticsExample from "./wizard-example/analytics-example.vue";
import DataChangeExample from "./wizard-example/data-change-example.vue";
import FieldBindingExample from "./wizard-example/field-binding-example.vue";
import HistoryExample from "./wizard-example/history-example.vue";
import LazyStepsExample from "./wizard-example/lazy-steps-example.vue";
import PersistencePluginExample from "./wizard-example/persistence-plugin-example.vue";
import PluginsExample from "./wizard-example/plugins-example.vue";
import ProviderExample from "./wizard-example/provider-example.vue";
import ResetCancelExample from "./wizard-example/reset-cancel-example.vue";
import StatePersistenceExample from "./wizard-example/state-persistence-example.vue";
import UseWizardExample from "./wizard-example/use-wizard-example.vue";

type Approach =
	| "use-wizard"
	| "provider"
	| "field-binding"
	| "history"
	| "reset-cancel"
	| "persistence"
	| "persistence-plugin"
	| "plugins"
	| "analytics"
	| "data-change"
	| "lazy-steps";

const approaches: Approach[] = [
	"use-wizard",
	"provider",
	"field-binding",
	"history",
	"reset-cancel",
	"persistence",
	"persistence-plugin",
	"plugins",
	"analytics",
	"data-change",
	"lazy-steps",
];

const approach = ref<Approach>("use-wizard");

onMounted(() => {
	const saved = localStorage.getItem("wizard-approach");
	if (saved && approaches.includes(saved as Approach)) {
		approach.value = saved as Approach;
	}
});

watch(approach, (newVal) => {
	localStorage.setItem("wizard-approach", newVal);
});
</script>

<template>
	<div class="min-h-screen bg-gray-50">
		<div class="max-w-7xl mx-auto py-8 px-4">
			<div class="mb-8">
				<h1 class="text-3xl font-bold text-gray-900">Vue Wizard Examples</h1>
				<p class="text-gray-600 mt-2">
					Demonstration of @gooonzick/wizard-vue adapter
				</p>
			</div>

			<ApproachToggle v-model="approach" class="mb-6" />

			<UseWizardExample v-if="approach === 'use-wizard'" />
			<ProviderExample v-else-if="approach === 'provider'" />
			<FieldBindingExample v-else-if="approach === 'field-binding'" />
			<HistoryExample v-else-if="approach === 'history'" />
			<ResetCancelExample v-else-if="approach === 'reset-cancel'" />
			<StatePersistenceExample v-else-if="approach === 'persistence'" />
			<PersistencePluginExample v-else-if="approach === 'persistence-plugin'" />
			<PluginsExample v-else-if="approach === 'plugins'" />
			<AnalyticsExample v-else-if="approach === 'analytics'" />
			<DataChangeExample v-else-if="approach === 'data-change'" />
			<LazyStepsExample v-else-if="approach === 'lazy-steps'" />
		</div>
	</div>
</template>
