// examples/react-examples/src/components/ui/card.tsx
import type * as React from "react";

import { cn } from "@/lib/utils";

function Card({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card"
			className={cn(
				"bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm",
				className,
			)}
			{...props}
		/>
	);
}

export { Card };

// examples/vue-examples/src/components/ui/card.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";

interface Props {
	class?: HTMLAttributes["class"];
}

defineProps<Props>();
</script>

<template>
	<div :class="cn('p-6 border rounded-md shadow-sm bg-card', $props.class)">
		<slot />
	</div>
</template>
