// examples/react-examples/src/components/validation-message.tsx
import { AlertCircle } from "lucide-react";
import type React from "react";

interface ValidationMessageProps {
	error?: string;
	className?: string;
}

export const ValidationMessage: React.FC<ValidationMessageProps> = ({
	error,
	className = "",
}) => {
	if (!error) return null;

	return (
		<div
			className={`flex items-center gap-2 text-red-600 text-sm mt-1 ${className}`}
		>
			<AlertCircle className="w-4 h-4 flex-shrink-0" />
			<span>{error}</span>
		</div>
	);
};

// examples/vue-examples/src/components/ui/validation-message.vue
<script setup lang="ts">
import { AlertCircle } from "@lucide/vue";

interface Props {
	error?: string;
}

defineProps<Props>();
</script>

<template>
	<div v-if="error" class="mt-1 flex items-center gap-1 text-sm text-destructive">
		<AlertCircle class="h-3 w-3" />
		<span>{{ error }}</span>
	</div>
</template>
